### ISSUE TITLE
Should unfold always add db name + version to SDF files?

### ISSUE THREAD

**Issue by marc-vdm** [polca/unfold#10]
Currently, when writing an SDF, you add database name + version
https://github.com/polca/unfold/blob/3e39224f99e73999cde00c4f3e0d1e4ae49f45fc/unfold/unfold.py#L1227

Would it be better if it was not added if a name is provided?

Reference: for ScenarioLink I'm already adding the (dependent) database name (e.g. ecoinvent 3.9) to the filename, e.g. my database in Brightway is called `ei391 - image - SSP1-Base`, and the SDF is now called `SDF ecoinvent 3.9 ei391 - image - SSP1-Base.csv`. 

IMO it would be most consistent if ScenarioLink chooses the name and it's the same as in AB, e.g. `SDF ei391 - image - SSP1-Base.csv`.

**Comment by romainsacchi** [comment]
Like so?

`            if self.name:
                filename = f"SDF {source_db['name']} {self.name}.csv"
            else:
                filename = f"SDF {source_db['name']} {source_db['version']} {self.package.descriptor['name']}.csv"
`

**Comment by marc-vdm** [comment]
Yes, I think so

**Comment by romainsacchi** [comment]
Re-open if it's no correct.
