### ISSUE TITLE
conda-forge release outdated

### ISSUE THREAD

**Issue by marc-vdm** [polca/unfold#11]
When installing ScenarioLink through `conda-forge`, an older version is installed:

```shell
(ab_sl_dependencies) C:\>conda list unfold
# packages in environment at C:\Users\meidemtvander\.conda\envs\ab_sl_dependencies:
#
# Name                    Version                   Build  Channel
unfold                    2023.10.07                 py_0    romainsacchi
```

This version is incompatible with the new `export_dir` variable.

**Comment by romainsacchi** [comment]
Are you sure? It says `2023.10.07`.

**Comment by marc-vdm** [comment]
Oops my bad, I was confused because pip uses semantic versioning
