### ISSUE TITLE
conflicting dependencies

### ISSUE THREAD

**Issue by mfastudillo** [polca/unfold#4]
unfold seems to be particularly useful when dealing with databases generated using premise but they seem to have conflicting requirements. unfold requires wurst==0.3.4 (https://github.com/polca/unfold/blob/main/requirements.txt) and premise wurst==0.3.3 (https://github.com/polca/premise/blob/master/requirements.txt)

**Comment by romainsacchi** [comment]
Hi @mfastudillo 
commit https://github.com/polca/unfold/commit/9832fd361f2747ee47de7155feaea1c483e30e9c changes the version specification of `wurst` to `>=0.3.3`.
