### ISSUE TITLE
improve examples

### ISSUE THREAD

**Issue by mfastudillo** [polca/unfold#5]
I think it would be helpful to improve the example provided in the repository. The example seems to assume we already have a premise database in our computer. It think this could be improved adding instructions on how to generate such database with premise.

Otherwise a very simple example with fictitious databases would work too.

**Comment by mfastudillo** [comment]
A simple fictitious example could be used as pytest fixture to expand the test coverage

**Comment by mfastudillo** [comment]
great, being picky here, but wouldn't it be better to call `bw2calc.LCA({bw2data.get_activity` instead of `bw.LCA({bw.get_activity` in the examples?. When I tried to run the example It resulted in errors because brightway2 was not installed (it is not part of the requirements). Everything worked fine when I used the imported bw2data and bw2calc

**Comment by romainsacchi** [comment]
Hi @mfastudillo, indeed, it's now fixed.
